export const OPEN_ERROR_ALERT_SNACKBAR = "OPEN_ERROR_ALERT_SNACKBAR";
export const OPEN_SUCCESS_ALERT_SNACKBAR = "OPEN_SUCCESS_ALERT_SNACKBAR";
export const CLOSE_ALERT_SNACKBAR = "CLOSE_ALERT_SNACKBAR";
