export const GET_INVENTORY_LIST_REQUEST = "GET_INVENTORY_LIST_REQUEST";
export const GET_INVENTORY_LIST_SUCCESS = "GET_INVENTORY_LIST_SUCCESS";
export const GET_INVENTORY_LIST_FAIL = "GET_INVENTORY_LIST_FAIL";

export const GET_DISTRIBUTABLE_INVENTORY_LIST_REQUEST =
  "GET_DISTRIBUTABLE_INVENTORY_LIST_REQUEST";
export const GET_DISTRIBUTABLE_INVENTORY_LIST_SUCCESS =
  "GET_DISTRIBUTABLE_INVENTORY_LIST_SUCCESS";
export const GET_DISTRIBUTABLE_INVENTORY_LIST_FAIL =
  "GET_DISTRIBUTABLE_INVENTORY_LIST_FAIL";

export const GET_RECEIVABLE_INVENTORY_LIST_REQUEST =
  "GET_RECEIVABLE_INVENTORY_LIST_REQUEST";
export const GET_RECEIVABLE_INVENTORY_LIST_SUCCESS =
  "GET_RECEIVABLE_INVENTORY_LIST_SUCCESS";
export const GET_RECEIVABLE_INVENTORY_LIST_FAIL =
  "GET_RECEIVABLE_INVENTORY_LIST_FAIL";

export const DISTRIBUTE_INVENTORY_REQUEST = "DISTRIBUTE_INVENTORY_REQUEST";
export const DISTRIBUTE_INVENTORY_SUCCESS = "DISTRIBUTE_INVENTORY_SUCCESS";
export const DISTRIBUTE_INVENTORY_FAIL = "DISTRIBUTE_INVENTORY_FAIL";
export const DISTRIBUTE_INVENTORY_RESET = "DISTRIBUTE_INVENTORY_RESET";

export const RECEIVE_RETURN_INVENTORY_REQUEST =
  "RECEIVE_RETURN_INVENTORY_REQUEST";
export const RECEIVE_RETURN_INVENTORY_SUCCESS =
  "RECEIVE_RETURN_INVENTORY_SUCCESS";
export const RECEIVE_RETURN_INVENTORY_FAIL = "RECEIVE_RETURN_INVENTORY_FAIL";
export const RECEIVE_RETURN_INVENTORY_RESET = "RECEIVE_RETURN_INVENTORY_RESET";

export const GET_INVENTORY_PRODUCT_REQUEST = "GET_INVENTORY_PRODUCT_REQUEST";
export const GET_INVENTORY_PRODUCT_SUCCESS = "GET_INVENTORY_PRODUCT_SUCCESS";
export const GET_INVENTORY_PRODUCT_FAIL = "GET_INVENTORY_PRODUCT_FAIL";
