export const CREATE_PROCUREMENT_REQUEST = "CREATE_PROCUREMENT_REQUEST";
export const CREATE_PROCUREMENT_SUCCESS = "CREATE_PROCUREMENT_SUCCESS";
export const CREATE_PROCUREMENT_FAIL = "CREATE_PROCUREMENT_FAIL";
export const CREATE_PROCUREMENT_RESET = "CREATE_PROCUREMENT_RESET";

export const GET_PROCUREMENT_LIST_REQUEST = "GET_PROCUREMENT_LIST_REQUEST";
export const GET_PROCUREMENT_LIST_SUCCESS = "GET_PROCUREMENT_LIST_SUCCESS";
export const GET_PROCUREMENT_LIST_FAIL = "GET_PROCUREMENT_LIST_FAIL";

export const UPDATE_PROCUREMENT_REQUEST = "UPDATE_PROCUREMENT_REQUEST";
export const UPDATE_PROCUREMENT_SUCCESS = "UPDATE_PROCUREMENT_SUCCESS";
export const UPDATE_PROCUREMENT_FAIL = "UPDATE_PROCUREMENT_FAIL";
export const UPDATE_PROCUREMENT_RESET = "UPDATE_PROCUREMENT_RESET";

export const DELETE_PROCUREMENT_REQUEST = "DELETE_PROCUREMENT_REQUEST";
export const DELETE_PROCUREMENT_SUCCESS = "DELETE_PROCUREMENT_SUCCESS";
export const DELETE_PROCUREMENT_FAIL = "DELETE_PROCUREMENT_FAIL";
export const DELETE_PROCUREMENT_RESET = "DELETE_PROCUREMENT_RESET";
