export const GET_PURCHASE_ORDER_LIST_REQUEST =
  "GET_PURCHASE_ORDER_LIST_REQUEST";
export const GET_PURCHASE_ORDER_LIST_SUCCESS =
  "GET_PURCHASE_ORDER_LIST_SUCCESS";
export const GET_PURCHASE_ORDER_LIST_FAIL = "GET_PURCHASE_ORDER_LIST_FAIL";

export const GET_PURCHASE_ORDER_REQUEST = "GET_PURCHASE_ORDER_REQUEST";
export const GET_PURCHASE_ORDER_SUCCESS = "GET_PURCHASE_ORDER_SUCCESS";
export const GET_PURCHASE_ORDER_FAIL = "GET_PURCHASE_ORDER_FAIL";

export const DELIVER_PURCHASE_ORDER_REQUEST = "DELIVER_PURCHASE_ORDER_REQUEST";
export const DELIVER_PURCHASE_ORDER_SUCCESS = "DELIVER_PURCHASE_ORDER_SUCCESS";
export const DELIVER_PURCHASE_ORDER_FAIL = "DELIVER_PURCHASE_ORDER_FAIL";
export const DELIVER_PURCHASE_ORDER_RESET = "DELIVER_PURCHASE_ORDER_RESET";

export const CONFIRM_DELIVERY_REQUEST = "CONFIRM_DELIVERY_REQUEST";
export const CONFIRM_DELIVERY_SUCCESS = "CONFIRM_DELIVERY_SUCCESS";
export const CONFIRM_DELIVERY_FAIL = "CONFIRM_DELIVERY_FAIL";
export const CONFIRM_DELIVERY_RESET = "CONFIRM_DELIVERY_RESET";
