export const CREATE_QUOTATION_REQUEST = "CREATE_QUOTATION_REQUEST";
export const CREATE_QUOTATION_SUCCESS = "CREATE_QUOTATION_SUCCESS";
export const CREATE_QUOTATION_FAIL = "CREATE_QUOTATION_FAIL";
export const CREATE_QUOTATION_RESET = "CREATE_QUOTATION_RESET";
